# Minimal Cloudflare Pages configuration
name = "google-review-widget"
compatibility_date = "2023-10-30"

# Pages configuration
pages_build_output_dir = "build"

# Environment variables
[vars]
NODE_VERSION = "20"

# Production environment vars
[env.production.vars]
NODE_VERSION = "20"

# Preview environment vars
[env.preview.vars]
NODE_VERSION = "20"
