name = "google-review-widget"
compatibility_date = "2023-08-01"

# The key property for Cloudflare Pages
pages_build_output_dir = "build"

# Configure KV namespace for caching
kv_namespaces = [
  { binding = "REVIEWS_KV", id = "your-kv-id-goes-here", preview_id = "your-preview-id-goes-here" }
]
