# Cloudflare Pages configuration

# Define the build command and output directory for SvelteKit
[build]
command = "npm run build"
destination = "build"

# Configure the environment variables needed for our deployment
[env.production]
NODE_VERSION = "20"  # Use Node.js 20 LTS

[env.preview]
NODE_VERSION = "20"  # Use Node.js 20 LTS
